language: node_js
node_js:
  - '11'
  - '10'
  - '8'
sudo: false
cache: npm

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script:
        - npm run test:full
      after_success:
        - npm run semantic-release
      branches:
        except:
          - /^v\d+\.\d+\.\d+$/
